### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by ghost** [alon22/cordova-plugin-firebase-mlvision#1]
I'm getting this problem when trying to build the app, you know what it could be?

![image](https://user-images.githubusercontent.com/13053339/83685430-0afe5c80-a5bf-11ea-9df3-74f71f8f00e4.png)

I am also using phonegap-plugin-push in version 2.2.3

**Comment by alon22** [comment]
I'm sorry to answer so late, there is a new version without Firebase. Try it and open a new issue if you find new problems
