### ISSUE TITLE
Feature request:  Position/bounding data

### ISSUE THREAD

**Issue by TSomKes** [alon22/cordova-plugin-firebase-mlvision#3]
Would you be willing to add positional/bounding information to your return data?

My team has used a few OCR plugins that provide approximately the same data:  the detected text, and also bounding coordinates for specific text blocks, lines and words.  (Example implementation:  https://bitbucket.org/bhivedevs/cordova-plugin-ml-text/src/master/)

Do you have access to this kind of position data, and would you consider adding a way for your plugin to provide it?

**Comment by alon22** [comment]
Yes, I have access to position data. It can be a good new feature.
Thanks.

**Comment by alon22** [comment]
I've publishes a new version with position data. I think that it's the correct info.
Open new issue if necessary

**Comment by TSomKes** [comment]
This is working well so far; thanks for the quick work.
