### ISSUE TITLE
Firebase ML Kit has been depreciated. Please update to use ML Kit SDK

### ISSUE THREAD

**Issue by farazahmadvaival** [alon22/cordova-plugin-firebase-mlvision#4]
This page describes an old version of the Text Recognition API, which was part of ML Kit for Firebase. The functionality of this API has been split into two new APIs (learn more):

On-device text recognition is part of the new standalone ML Kit SDK, which you can use with or without Firebase.
Cloud text recognition is part of Firebase ML, which includes all of Firebase's cloud-based ML features.

**Comment by alon22** [comment]
I'm working in it. There will be a new release soon. [feature/migrate-to-googlemlkit](https://github.com/alon22/cordova-plugin-firebase-mlvision/tree/feature/migrate-to-googlemlkit)

**Comment by alon22** [comment]
Updated to ML Kit SDK [https://github.com/alon22/cordova-plugin-firebase-mlvision/tree/master](https://github.com/alon22/cordova-plugin-firebase-mlvision/tree/master)
