### ISSUE TITLE
File google-services.json is missing

### ISSUE THREAD

**Issue by martinmitteregger** [alon22/cordova-plugin-firebase-mlvision#8]
I'm using your plugin with Ionic and get the error `File google-services.json is missing. The Google Services Plugin cannot function without it.` when compiling/running the app.
Is the google-services.json still necessary?

**Comment by alon22** [comment]
what version are you using? With version 0.3.0 it should not be necessary

**Comment by martinmitteregger** [comment]
Currently I'm using version 0.3.0 - maybe its unused but some part of the plugin seems to "need" the file

**Comment by alon22** [comment]
Fixed in version [0.3.1](https://github.com/alon22/cordova-plugin-firebase-mlvision/tree/0.3.1)
